export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d0e1fb",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-container": "#ffede6",
        "outline-variant": "#c3c6d7",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-container": "#54647a",
        "tertiary-container": "#bc4800",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed": "#00174b",
        "primary-container": "#2563eb",
        "surface-tint": "#0053db",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed": "#360f00",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb596",
        "background": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        "secondary": "#505f76",
        "inverse-primary": "#b4c5ff",
        "surface-container": "#eceef0",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "primary": "#004ac6",
        "on-tertiary": "#ffffff",
        "outline": "#737686",
        "inverse-surface": "#2d3133",
        "tertiary": "#943700",
        "on-surface": "#191c1e",
        brand: {
          50:  '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2b7de9',
          700: '#1a61cc',
          800: '#1e40af',
          900: '#1e3a8a',
        }
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "xl": "2rem",
        "md": "1rem",
        "lg": "1.5rem",
        "margin-desktop": "2.5rem",
        "base": "4px",
        "xs": "0.25rem",
        "sm": "0.5rem"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: []
};
